version: "3.8"
services:
  client:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
